// STRINGS USED IN UI
const strings = {
  healthDashborad: 'Health Dashboard',
  weight: 'Weight',
  other: 'Other - Leg infection',
  healthTracker: 'Health Tracker',
  services: 'Services',
  titleServices: 'Pharmaceuticals to get your pet feeling better. Prescription needed.',
  categoryServices: 'Lorem Ipsum iscdd  foren simply dummy text',
  selectVet: 'Select a vet',
  titleVet: 'Find someone who specialises in your pet.',
  availDocs: '15 available doctors',
  docName: 'Dr. Mark Wayne',
  docSpl: 'Nutritionist',
  address: 'Egmore, Chennai',
  book: 'Book Consultation',
  details: 'Details', clinicAdd: 'Clinic Address',
  clinicAddress: '12, 1st road' + '\n' + 'Egmore main street, Dawkar Nagar' + '\n' + 'Chennai -435345',
  about: 'About',
  loream: 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document used to demonstrate the visual form of a document ',
  email: 'Email ID',
  mail: 'shankarkumar@email.com',
  contactNo: 'Contact Number',
  contactNum: '403-949-6478',
  experience: 'Experience',
  years: '2 Years',
  consultType: 'Consultation Type Available',
  type: 'Video, Physical',
  selectType: 'Select Consulatation Type',
  reason: 'Reason for Consultation',
  next: 'Next',
  selectDate: 'Select Date',
  availSlot: 'Available Slot',
  description: 'Description',
  checkOut: 'Checkout',
  upload: 'Upload Prescription or Report',
  uploadtext: 'Upload JPEG or PDF File',
  conDetails: 'Consultation details',
  paymentSummary: 'Payment summary',
  makePayment: 'Make Payment',

  // Articles
  info: 'Information',
  recommend: 'Recommend Articles',
  seeAll: 'See All',
  healthy: 'How to maintain a healthy routine',
  essential: 'Essential Puppy care',
  healthArticle: 'Health Articles',
  articleLoream: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  mostPopular: 'Most Popular Articles',
  loreamArticle: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  relatedArticle: 'Related Articles',
  grooming: 'Grooming Articles',

  // Shop flow
  omega: 'Omega Tablet for Adult Dog',
  tabletLorem: 'Lorem Ipsum iscdd  foren simply dummy text of the Lorem Ipsum iscdd  foren simply dummy text of the Lorem Ipsum iscdd  foren simply',
  buyNow: 'Buy Now',
  addToCart: 'Add to Cart',
  confirmProduct: 'Confirm Product',
  confirmTxt: 'Are you sure you want to Buy the product',
  yes: 'Yes',
  no: 'No',
  similarProd: 'Similar products',
  yourCart: 'Your cart',
  applyCoupon: 'Apply Coupon Code',
  unlock: 'Unlock offers with coupon codes',
  soldOut: 'Sold out',
  available: 'Only 4 Available',
  detailsOfOmega: 'Details',
  subTotal: 'Subtotal',
  taxAndDelivery: 'Taxes and delivery',
  toPay: 'To Pay',
  selectAddress: 'Select Address',
  checkOutTitle: 'Checkout',
  harryUp: 'Hurry! save 25% on medicine',
  couponLorem: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fringilla conts pharetra, morbi',
  validTill: 'Valid Till: June 22',
  code: 'Code: PAS200',
  couponPlaceholder: 'Apply your coupon code here',
  applyCouponText: 'Apply Coupon',
  newAddress: 'New Address',
  home: 'Home',
  homeText: 'Random address for Home saved in the app 12th street random location address',
  work: 'Work',
  friendHouse: "Friend's House",
  reviewOrder: 'Review Order',
  name: 'Name',
  address1: 'Address 1',
  address2: 'Address 2',
  postalCode: 'Postal Code',
  mobileNum: 'Mobile Number',
  typeText: 'Type',
  add: 'Add',
  addNewAddress: 'Add New Address',
  selectPayment: 'Select Payment Method',

};

const placeholders = {
  enterEmail: 'Enter your Email',
  enterPassword: 'Enter your Password',
};

export { strings, placeholders };
